### PR TITLE
Create seeding data and db connection for nearby houses 

### PR DESCRIPTION
**Pull request by tjlee527**

### CODE REVIEW

**Comment by tjlee527** [comment]
@KeitelDOG, remade new repo with correct starter code and .gitignore, copied over my code and seeding script is able to run. Please review!

**Comment by KeitelDOG** [comment]
@tjlee527 seems good.

**Comment by KeitelDOG** [comment]
@tjlee527  I don't see codes that push the sample data to MongoDB yet, so don't forget to do it in another PR

**Comment by tjlee527** [comment]
@KeitelDOG I have it in seed.js, i think its just not showing bc the file is too big

**Pull request merged**
